---
- name: Create AKS Cluster
  hosts: localhost
  connection: local
  vars:
    resource_group: "my-aks-rg"
    cluster_name: "my-aks-cluster"
    location: "eastus2"
    node_count: 2
    vm_size: "Standard_B2s"
  tasks:
    - name: Login to Azure
      shell: |
        az login --service-principal \
          -u "{{ lookup('env', 'AZ_CLIENT_ID') }}" \
          -p "{{ lookup('env', 'AZ_CLIENT_SECRET') }}" \
          --tenant "{{ lookup('env', 'AZ_TENANT_ID') }}"
        az account set --subscription "{{ lookup('env', 'AZ_SUBSCRIPTION_ID') }}"

    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create AKS cluster
      azure.azcollection.azure_rm_aks:
        name: "{{ cluster_name }}"
        resource_group: "{{ resource_group }}"
        dns_prefix: "vipinaks"
        kubernetes_version: "1.29.0"
        location: "{{ location }}"
        node_count: "{{ node_count }}"
        vm_size: "{{ vm_size }}"
        enable_rbac: true
        enable_managed_identity: true

    - name: Get AKS credentials
      shell: |
        az aks get-credentials -g {{ resource_group }} -n {{ cluster_name }} --overwrite-existing
